### ISSUE TITLE
Need your advice: begin from Bioasq or baseqa

### ISSUE THREAD

**Issue by noyessie** [oaqa/bioasq#4]
> Please, excuse me but my english writing is not well. my question maybe stupid, but i need your help.

I want to make a question answering system for cyber security domain. I have got a small knowledge graph of cybersecurity domain and a big datasets of pdf files.

My question is that: ` what do you recommend me to do ? adapt from bioasq or from baseqa`

Now, I sereously learn bioasqa systems and i think, i understant the code logic and the pipeline process for answertype classification and he work fine. But i have a strong difficulty to continue on document/snippets/concepts retrieval , and answer generation. 

I think these part of bioasq pipeline is hardly adapted to Bioasq challenge and the different algorithms you use here is adapted to BioASQ dataset. It is correct ??

@ziy I read your publications and your thesis. But, It remains flour.

Please one advice.

Thank in advance.

**Comment by ziy** [comment]
Thanks for your question and your interest.

First of all, you want to make sure if you have example questions and ground truth answers. If not, then probably you do want to collect a few to begin with, using wikipedia’ info box for example.

If you’ve got the gold standard Q/A pairs, then you could probably consider a OAQA BioASQ style QA system. In fact, the final answer is generated from the "answer scoring” step. You can think of all the previous steps are preparation steps or feature generation steps for this final prediction. If you don’t have a good NLP parser for cyber security domain, you could just use the ordinary English parser, if you don’t have a good synonym dictionary, you can also skip the concept identification and search steps too. In the end, you might just have fewer features of possibly lower quality, but the system should still work.

A few more things in case you are not aware of for your problem.

1. The current OAQA BioASQ system doesn’t use a knowledge graph directly in answer generation. If you believe this is the most important source of information, then you might think of other alternative procedure, which usually starts with a full syntactic/semantic question parsing, then followed by a SparQL query generation.

2. You might need to retrain the models. For some phases, e.g. document retrieval, where you have a ground truth output for each input, then you can train directly. Otherwise, e.g. answer type prediction, you should use an additional taxonomy and obtain the answer types for the gold standard answers.

3. Regarding the pdfs, you might find a pdf parser that helps you extract the useful content. But the pdf files are images, scanner or converted from other image format, then this won’t give you too much information. I would suggest before you consider the online QA pipeline, you can now focus on the offline preprocessing steps (including pdf preprocessing, and the above mentioned ground truth collection, etc.), since you do have to deal with these preprocessing steps regardless what the on-line QA system looks like.

Let me know if you have any other questions.

-- 
Zi Yang
PhD Candidate
Language Technologies Institute
School of Computer Science
Carnegie Mellon University
HP: http://www.cs.cmu.edu/~ziy <http://www.cs.cmu.edu/~ziy>

**Comment by noyessie** [comment]
thank for your answer.

I finally build a end-to-end pipeline. but the answers are realy bad. 

Now i trying to put a domain tools like cybersecurity NER, cybersecurity dictionnaire and i hope the quality is imporved.

**Comment by ziy** [comment]
You are right. The system gives you a framework and a few baseline components to play with, but you might want to carefully look into the system output at each step. Then, you may want to consider to change the configuration a little bit. For example, if the dataset is noisy, then probably, you want to select only the top 1 or 2 sentences for answer extraction, rather than 10 or 100.

-- 
Zi Yang
PhD
Language Technologies Institute
School of Computer Science
Carnegie Mellon University
HP: http://www.cs.cmu.edu/~ziy <http://www.cs.cmu.edu/~ziy>
